### ISSUE TITLE
Null pointer exemption (encoder.go)

### ISSUE THREAD

**Issue by Ahudeda** [pandatix/nvdapi#8]
https://github.com/pandatix/nvdapi/blob/11bc999ed1b9c8c65857c8e2a7e48f2aeed3c0b6/v2/cve.go#L30C1-L33C61

	VersionStart       *string `nvd:"versionStart,omitempty"`
	VersionStartType   *string `nvd:"versionStartType,omitempty"`
	VersionEnd         *string `nvd:"versionEnd,omitempty"`
	VersionEndType     *string `nvd:"versionEndType,omitempty"`
every line missing trailing comma
null pointer on encoder.go (if pts[2] == "noValue" && f.Kind() == reflect.Bool && f.Bool() {)

**Comment by pandatix** [comment]
Hi @Ahudeda,


Thanks for finding this mistake. I will fix it soon (under <48h) when available, or accept a PR if one pops up.

Bests, Lucas.

**Comment by pandatix** [comment]
Hey, should be fixed by [v0.6.5](https://github.com/pandatix/nvdapi/tree/v0.6.5) :wink:
